### ISSUE TITLE
Roll back Chart fix once Telerik fix is in place

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#818]
**Overview:** from #808, we had to put a work around for fixing a dark theme issue.  Once Telerik rolls out a fix, we'll fix it.  

Link to their tracking issue:  https://github.com/telerik/UI-For-UWP/issues/147

**Comment by mrlacey** [comment]
Latest from Telerik: This is an issue related to something done by Microsoft in the creators update (my guess is changing of theme names) that should hopefully be addressed in the FCU.
I think this means this bug is going to be around as long as we support targeting the CU as unlikely to be fixed by Telerik.

**Comment by dgomezc** [comment]
Just tested in a FCU machine and still happend. Moving to one 1.5 to check it once FCU is in RTM.

**Comment by ralarcon** [comment]
Moving to the backlog and marking as external as we depend on telerik fix to be released.

**Comment by sibille** [comment]
Fixed on latest version of telerik (1.0.1.1). We'll try to update and remove workaround for version 2.4.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18257.1
Wizard version: 0.18.18257.1
