### ISSUE TITLE
Remove SA1008 suppression for tuples once stylecop is updated

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#874]
When https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2308 is fixed, remove the few spots we use tuples for return types.

`[SuppressMessage("StyleCop", "SA1008", Justification = "StyleCop doesn't understand C#7 tuple return types yet.")]`

**Comment by crutkas** [comment]
we can update to 1.1.0 b4 and this is fixed.

**Comment by crutkas** [comment]
@sibille looking at the style cop issue, this is fixed

**Comment by mrlacey** [comment]
A search of the `big` solution still shows 24 uses of SA1008 in 10 files.

**Comment by sibille** [comment]
Verified in dev
